// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ2fbCfmpuylySqBm_74jY-JFpF9stYW8',
    appId: '1:66418884443:web:71a6cfa2da21943844e47e',
    messagingSenderId: '66418884443',
    projectId: 'projeto-receitas-34bb5',
    authDomain: 'projeto-receitas-34bb5.firebaseapp.com',
    storageBucket: 'projeto-receitas-34bb5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0S8q3mzU9RJ5cOV4jE8ISdh2cp2GtgIA',
    appId: '1:66418884443:android:eab2045c8218e02044e47e',
    messagingSenderId: '66418884443',
    projectId: 'projeto-receitas-34bb5',
    storageBucket: 'projeto-receitas-34bb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCANXx68U7CIn_BEGw-WFNOMj4yHCa2xuM',
    appId: '1:66418884443:ios:7f92b93792d4205344e47e',
    messagingSenderId: '66418884443',
    projectId: 'projeto-receitas-34bb5',
    storageBucket: 'projeto-receitas-34bb5.firebasestorage.app',
    iosBundleId: 'com.example.projetoReceitas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCANXx68U7CIn_BEGw-WFNOMj4yHCa2xuM',
    appId: '1:66418884443:ios:7f92b93792d4205344e47e',
    messagingSenderId: '66418884443',
    projectId: 'projeto-receitas-34bb5',
    storageBucket: 'projeto-receitas-34bb5.firebasestorage.app',
    iosBundleId: 'com.example.projetoReceitas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ2fbCfmpuylySqBm_74jY-JFpF9stYW8',
    appId: '1:66418884443:web:4e92e8c78f2fc70a44e47e',
    messagingSenderId: '66418884443',
    projectId: 'projeto-receitas-34bb5',
    authDomain: 'projeto-receitas-34bb5.firebaseapp.com',
    storageBucket: 'projeto-receitas-34bb5.firebasestorage.app',
  );
}
